# Generated by Django 5.1 on 2024-08-25 06:38

from django.db import migrations

def transfer_categories(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.category:
            product.categories.add(product.category)
            product.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_categories),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]