# Generated by Django 5.1 on 2024-09-08 08:58

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_review_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='product_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='products/'),
        ),
    ]
